all:
	make -f ascii_table.mk all
	make -f ascii_table_extended.mk all
	make -f echo.mk all
	make -C compare all

clean:
	make -f ascii_table.mk clean
	make -f ascii_table_extended.mk clean
	make -f echo.mk clean
	make -C compare clean

