all:
	make -f ascii_table.mk all
	make -f ascii_table_extended.mk all

clean:
	make -f ascii_table.mk clean
	make -f ascii_table_extended.mk clean

install: all
	make -f ascii_table.mk install
	make -f ascii_table_extended.mk install

