#
# Makefile - top level make for fabooh examples
#
# includes.mk can be used to change MCU and BOARD variants
#

all:
	@make -C examples/basic all
	@make -C examples/lcd all
	@make -C examples/math all
	@make -C examples/serial all

clean:
	@make -C examples/basic clean
	@make -C examples/lcd clean
	@make -C examples/math clean
	@make -C examples/serial clean
	
